version: '3'

services:
  db:
    image: "postgres:10.4"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "account_service"
      POSTGRES_USER: "account-service"
      POSTGRES_PASSWORD: "account-s3rv1c3"
  app:
    image: 'mhbp2021/accounts-service:0.0.3-SNAPSHOT'
    ports:
      - "8300:8300"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/account_service
      - SPRING_DATASOURCE_USERNAME=account-service
      - SPRING_DATASOURCE_PASSWORD=account-s3rv1c3
