
CREATE TABLE TRANSACTIONS
(
    id                     BIGINT NOT NULL     CONSTRAINT transactions_pkey PRIMARY KEY ,
    ACCOUNT_ID             BIGINT NOT NULL,
    OPERATION_TYPE_ID      INT CHECK (OPERATION_TYPE_ID >= 1 and OPERATION_TYPE_ID <= 4) NOT NULL,
    AMOUNT                 MONEY  NOT NULL,
    EVENT_DATE             TIMESTAMP NOT NULL

);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TO_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);
CREATE SEQUENCE SQ_TRANSACTIONS START WITH 1 INCREMENT BY 1 ;
